name: CI Build NTK on Certain Branch
on:
  workflow_call:
    inputs:
      runner_labels:
        required: false
        type: string

jobs:
  build-image:
    name: Build Image
    runs-on: ${{ inputs.runner_labels  || 'self-hosted' }}
    steps:
      - name: Prepare Vars
        id: prep
        run: |
          echo "Put some logic here!"