name: CI Build NTK on Push TAG
on:
  workflow_call:
    inputs:
      runner_labels:
        required: false
        type: string

jobs:
  deploy-pages:
    permissions:
      contents: write
    name: Deploy Pages
    runs-on: ${{ inputs.runner_labels  || 'self-hosted' }}
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
        with:
          persist-credentials: false

      - name: Delete Tag
        uses: dev-drprasad/delete-tag-and-release@82600feb9527126eca69833f07bafe53279bd9b4 # v1.1
        with:
          tag_name: ${{ github.ref_name }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean Materials
        run: mkdir -p ./mkdocs-material/material

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@d77dd03172e96abbcdb081d8c948224762033653 # 1.26
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: ./mkdocs.yml
          REQUIREMENTS: ./modules.txt

  notify-telegram:
    permissions:
      contents: read
    name: Notifier
    runs-on: ${{ inputs.runner_labels  || 'self-hosted' }}
    if: always()
    needs: deploy-pages
    steps:
      - name: Set Telegram Message
        uses: novaitdevteam/nova.ci/.github/actions/action-cond@main
        id: telegram_message
        with:
          cond: ${{ contains(join(needs.*.result, ','), 'success') }}
          if_true: |
            👷 ${{ github.actor }} created deploy tag.

            GitHub Pages assembly has been completed ✅

            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}
          if_false: |
            👷 ${{ github.actor }} created deploy tag.

            ❌Build Failed

            🔗 See Details: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            Repository: ${{ github.repository }}

      - name: Notify
        uses: novaitdevteam/nova.ci/.github/actions/notify@main
        with:
          message: ${{ steps.telegram_message.outputs.value }}
          telegram_token: ${{ secrets.TG_NOTIFICATION_BOT_TOKEN }}
          telegram_to: ${{ secrets.TG_NOTIFICATION_BOT_ID }}
